### PR TITLE
#160584003 users should be able to follow each other

### PR DESCRIPTION
**Pull request by balaakagordon**
#### What does this PR do?
`allows users to follow each other and to manage people they are following`
#### Description of Task to be completed?
Have the following endpoints working:
`POST api/profile/<str:username>/follow/`
`DELETE api/profile/<str:username>/unfollow/`
`GET api/profile/<str:username>/following/`
`GET api/profile/<str:username>/followers/`
#### How should this be manually tested?
After pulling the changes from this branch migrations should be made using:
```
 - $ python manage.py makemigrations articles
 - $ python manage.py makemigrations authentication
 - $ python manage.py makemigrations profiles
 - $ python manage.py migrate 
```

Using Postman to run the application, you can run the endpoints above to:
```
- follow users
- unfollow users
- look at your followers
- look at other users' followers
- look at users you are following
- look at users other users are following
```
#### What are the relevant pivotal tracker stories?
#160584003 - Users should be able to follow each other
#### Screenshots (if appropriate)
Get users who you are following
image

Get followers
image

Message after following "tester4"
image

Message after unfollowing "tester4"
image

#### Questions:

### CODE REVIEW

**Comment by kenneth051** [comment]
Hey @balaakagordon, good job man. 
I have noticed conflicts between your branch and develop. Could you please look into it?
Otherwise, good work!

**Review by kenneth051 — COMMENTED** [review]
For the code climate issue, Prossy refactored most of the code. So I think we should wait until her pull request is merged and we rebase.

**Comment by JoyLubega** [comment]
Rebase

**Comment by Edward-K1** [comment]
Good work @balaakagordon , please fix the merge conflicts so that I can test your work. One other thing I'd like to point out is, whenever you modify or add a model it is always good to add the `migration commands` to how your work can be manually tested.

**Review by j0flintking02 — APPROVED** [review]
LGTM

**Comment by kenneth051** [comment]
LGTM

**Review by nakimera — COMMENTED** [review]
LGTM

**Pull request merged**
