### PR TITLE
#160584001 User should be able to comment on an article

### PR DESCRIPTION
**Pull request by j0flintking02**
#### What does this PR do?
    Users should be able to comment on an article
    
#### Description of Task to be completed?
    - implement posting and retrieving comments
    - implement error handling for failed delivery
#### How should this be manually tested?
- One can be to view the comments without the use of the token
Get all comments on an article
> articles/<str:slug>/comments/ [GET]

Add a comment on an article
 - One can only add a comment if the they have a token 
> articles/<str:slug>/comments/ [POST]
```json
    {
  "comment": {
    "body": "this is some other comment"
  }
}
```
add replies to a comment
> /api/articles/<str:slug>/comments/<int:id>/ [POST]
```json
    {
  "reply": {
    "body": "this is some other comment"
  }
}
```

View single comment on the article
> /api/articles/<str:slug>/comments/<int:id>/ [GET]

```json
{
    "Comments": [
        {
            "id": 1,
            "user": 1,
            "body": "His name was my name too.",
            "article": 1,
            "created_at": "2018-10-11T20:24:15.910371Z",
            "updated_at": "2018-10-11T20:24:15.910391Z",
            "replies": [
                {
                    "id": 2,
                    "body": "His name was my name too.",
                    "updated_at": "2018-10-11T20:25:55.422606Z"
                },
                {
                    "id": 3,
                    "body": "His name was my name too.",
                    "updated_at": "2018-10-11T20:25:59.769010Z"
                }
            ]
        }
    ]
}
```

Delete a comment from the article
> /api/articles/<str:slug>/comments/<int:id>/ [POST]

### CODE REVIEW

**Comment by balaakagordon** [comment]
LGTM! Good work Jonah. The files and features look fine to me and your tests are all passing

**Comment by nakimera** [comment]
hi @j0flintking02. Good job. Your code is readable and the tests are passing. However, this can be improved when you rebase. Please could consider docstrings to give us a short description of what each unit test does. Also, consider removing the commented out mock login in your tests and moving the "data" [lines 148 & 160 - test_articles.py] to the BaseTest file. Lastly, can you draw more light on adding a comment? Does a user need a token to do so?

**Comment by j0flintking02** [comment]
> hi @j0flintking02. Good job. Your code is readable and the tests are passing. However, this can be improved when you rebase. Please could consider docstrings to give us a short description of what each unit test does. Also, consider removing the commented out mock login in your tests and moving the "data" [lines 148 & 160 - test_articles.py] to the BaseTest file. Lastly, can you draw more light on adding a comment? Does a user need a token to do so?

I have implemented the feedback that you had pointed out but the reason I hesitated to add comments to the test is cause I have tried my best to make my test self-documented if that is ok

**Comment by Edward-K1** [comment]
@j0flintking02 , 👇 
image

**Are you posting comments or articles?**

**Comment by j0flintking02** [comment]
> @j0flintking02 , 👇
> image
> 
> Are you posting comments or articles?

I have just edited that thanks for noting that out @Edward-K1

**Comment by kenneth051** [comment]
@j0flintking02  good work. The feature works as expected.

**Comment by JoyLubega** [comment]
Rebase

**Pull request merged**
