### PR TITLE
#160584010 Add search for articles

### PR DESCRIPTION
**Pull request by Edward-K1**
### What does this PR do?
It adds search for articles

### Description of the tasks to be completed.
A user should be able to filter articles by author
A user should be able to filter articles by tag
A user should be able to filter by keywords
A user should be able to combine all the above search criteria to filter articles

### How can this be manually tested?
```
git checkout ft-add-article-search-160584010
python manage.py makemigrations authentication
python manage.py makemigrations profiles
python manage.py makemigrations articles
python manage.py migrate
python manage.py runserver
```
### Screenshots
search_by_author

search_by_tag

search_by_keywords

Pivotal Tracker ID:
#160584010

### CODE REVIEW

**Review by balaakagordon — APPROVED** [review]
Great work!

**Comment by kenneth051** [comment]
LGTM

**Review by nakimera — APPROVED** [review]
LGTM

**Review by j0flintking02 — APPROVED** [review]
LGTM

**Pull request merged**
