### PR TITLE
Add image support to articles [Delivers #160583999]

### PR DESCRIPTION
**Pull request by Edward-K1**
### What does this PR do?
It adds an image field to articles.

### Description of the tasks to be completed.

A user adds an image to an article by supplying its url as shown in the screenshots below.

### How can this be manually tested?
```
git checkout ft-create-article-160583999
python manage.py makemigrations
python manage.py migrate
python manage.py runserver
```

**Screenshot for creating an article with an image**
article_with_image

**Screenshot for updating the image of an article**
updated_image

**Screenshot for getting all articles**
getting_articles_with_image

**Screenshot of running server**
article_with_image_running_server

### Pivotal Tracker ID:
**#160583999**

### CODE REVIEW

**Comment by nakimera** [comment]
Your code is readable and looks good to go. Is the image part tested though?

**Comment by Edward-K1** [comment]
Thanks @nakimera. The image field was tested as shown in the screenshots.

**Review by kenneth051 — COMMENTED** [review]
This is straight forward.. it's fine.

**Comment by JoyLubega** [comment]
LGTM!

**Pull request merged**
